apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: multi-container
spec:
  containers:

    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80

    - name: ubuntu
      image: ubuntu:latest
      command: ["/bin/bash", "-c"]
      args:
        - |
          while true; do
            echo "Ubuntu container is running..."
            sleep 10
          done